// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: atomic.ally.xiao.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AtomicAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Delta int64  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
}

func (x *AtomicAddRequest) Reset() {
	*x = AtomicAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_ally_xiao_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomicAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicAddRequest) ProtoMessage() {}

func (x *AtomicAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_ally_xiao_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicAddRequest.ProtoReflect.Descriptor instead.
func (*AtomicAddRequest) Descriptor() ([]byte, []int) {
	return file_atomic_ally_xiao_proto_rawDescGZIP(), []int{0}
}

func (x *AtomicAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AtomicAddRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type AtomicAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val int64 `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *AtomicAddResponse) Reset() {
	*x = AtomicAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_ally_xiao_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomicAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicAddResponse) ProtoMessage() {}

func (x *AtomicAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_ally_xiao_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicAddResponse.ProtoReflect.Descriptor instead.
func (*AtomicAddResponse) Descriptor() ([]byte, []int) {
	return file_atomic_ally_xiao_proto_rawDescGZIP(), []int{1}
}

func (x *AtomicAddResponse) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type AtomicCompareAndSwapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Old  int64  `protobuf:"varint,2,opt,name=old,proto3" json:"old,omitempty"`
	New  int64  `protobuf:"varint,3,opt,name=new,proto3" json:"new,omitempty"`
}

func (x *AtomicCompareAndSwapRequest) Reset() {
	*x = AtomicCompareAndSwapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_ally_xiao_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomicCompareAndSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicCompareAndSwapRequest) ProtoMessage() {}

func (x *AtomicCompareAndSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_ally_xiao_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicCompareAndSwapRequest.ProtoReflect.Descriptor instead.
func (*AtomicCompareAndSwapRequest) Descriptor() ([]byte, []int) {
	return file_atomic_ally_xiao_proto_rawDescGZIP(), []int{2}
}

func (x *AtomicCompareAndSwapRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AtomicCompareAndSwapRequest) GetOld() int64 {
	if x != nil {
		return x.Old
	}
	return 0
}

func (x *AtomicCompareAndSwapRequest) GetNew() int64 {
	if x != nil {
		return x.New
	}
	return 0
}

type AtomicCompareAndSwapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Swapped bool `protobuf:"varint,1,opt,name=swapped,proto3" json:"swapped,omitempty"`
}

func (x *AtomicCompareAndSwapResponse) Reset() {
	*x = AtomicCompareAndSwapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_ally_xiao_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomicCompareAndSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicCompareAndSwapResponse) ProtoMessage() {}

func (x *AtomicCompareAndSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_ally_xiao_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicCompareAndSwapResponse.ProtoReflect.Descriptor instead.
func (*AtomicCompareAndSwapResponse) Descriptor() ([]byte, []int) {
	return file_atomic_ally_xiao_proto_rawDescGZIP(), []int{3}
}

func (x *AtomicCompareAndSwapResponse) GetSwapped() bool {
	if x != nil {
		return x.Swapped
	}
	return false
}

type AtomicLoadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AtomicLoadRequest) Reset() {
	*x = AtomicLoadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_ally_xiao_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomicLoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicLoadRequest) ProtoMessage() {}

func (x *AtomicLoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_ally_xiao_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicLoadRequest.ProtoReflect.Descriptor instead.
func (*AtomicLoadRequest) Descriptor() ([]byte, []int) {
	return file_atomic_ally_xiao_proto_rawDescGZIP(), []int{4}
}

func (x *AtomicLoadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AtomicLoadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val int64 `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *AtomicLoadResponse) Reset() {
	*x = AtomicLoadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_ally_xiao_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomicLoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicLoadResponse) ProtoMessage() {}

func (x *AtomicLoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_ally_xiao_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicLoadResponse.ProtoReflect.Descriptor instead.
func (*AtomicLoadResponse) Descriptor() ([]byte, []int) {
	return file_atomic_ally_xiao_proto_rawDescGZIP(), []int{5}
}

func (x *AtomicLoadResponse) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type AtomicStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Val  int64  `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *AtomicStoreRequest) Reset() {
	*x = AtomicStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_ally_xiao_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomicStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicStoreRequest) ProtoMessage() {}

func (x *AtomicStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_ally_xiao_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicStoreRequest.ProtoReflect.Descriptor instead.
func (*AtomicStoreRequest) Descriptor() ([]byte, []int) {
	return file_atomic_ally_xiao_proto_rawDescGZIP(), []int{6}
}

func (x *AtomicStoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AtomicStoreRequest) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type AtomicStoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AtomicStoreResponse) Reset() {
	*x = AtomicStoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_ally_xiao_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomicStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicStoreResponse) ProtoMessage() {}

func (x *AtomicStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_ally_xiao_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicStoreResponse.ProtoReflect.Descriptor instead.
func (*AtomicStoreResponse) Descriptor() ([]byte, []int) {
	return file_atomic_ally_xiao_proto_rawDescGZIP(), []int{7}
}

type AtomicSwapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	New  int64  `protobuf:"varint,2,opt,name=new,proto3" json:"new,omitempty"`
}

func (x *AtomicSwapRequest) Reset() {
	*x = AtomicSwapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_ally_xiao_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomicSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicSwapRequest) ProtoMessage() {}

func (x *AtomicSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_ally_xiao_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicSwapRequest.ProtoReflect.Descriptor instead.
func (*AtomicSwapRequest) Descriptor() ([]byte, []int) {
	return file_atomic_ally_xiao_proto_rawDescGZIP(), []int{8}
}

func (x *AtomicSwapRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AtomicSwapRequest) GetNew() int64 {
	if x != nil {
		return x.New
	}
	return 0
}

type AtomicSwapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Old int64 `protobuf:"varint,1,opt,name=old,proto3" json:"old,omitempty"`
}

func (x *AtomicSwapResponse) Reset() {
	*x = AtomicSwapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_ally_xiao_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomicSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicSwapResponse) ProtoMessage() {}

func (x *AtomicSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_ally_xiao_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicSwapResponse.ProtoReflect.Descriptor instead.
func (*AtomicSwapResponse) Descriptor() ([]byte, []int) {
	return file_atomic_ally_xiao_proto_rawDescGZIP(), []int{9}
}

func (x *AtomicSwapResponse) GetOld() int64 {
	if x != nil {
		return x.Old
	}
	return 0
}

var File_atomic_ally_xiao_proto protoreflect.FileDescriptor

var file_atomic_ally_xiao_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x78, 0x69,
	0x61, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61,
	0x6c, 0x6c, 0x79, 0x22, 0x3c, 0x0a, 0x10, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64,
	0x65, 0x6c, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x74,
	0x61, 0x22, 0x25, 0x0a, 0x11, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x55, 0x0a, 0x1b, 0x41, 0x74, 0x6f, 0x6d,
	0x69, 0x63, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x77, 0x61, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f,
	0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x6c, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6e, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x65, 0x77, 0x22,
	0x38, 0x0a, 0x1c, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65,
	0x41, 0x6e, 0x64, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x77, 0x61, 0x70, 0x70, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x77, 0x61, 0x70, 0x70, 0x65, 0x64, 0x22, 0x27, 0x0a, 0x11, 0x41, 0x74, 0x6f,
	0x6d, 0x69, 0x63, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x26, 0x0a, 0x12, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x4c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x3a, 0x0a, 0x12, 0x41, 0x74,
	0x6f, 0x6d, 0x69, 0x63, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x15, 0x0a, 0x13, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a,
	0x11, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x65, 0x77, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x65, 0x77, 0x22, 0x26, 0x0a, 0x12, 0x41, 0x74, 0x6f, 0x6d,
	0x69, 0x63, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x6c, 0x64,
	0x32, 0x9d, 0x03, 0x0a, 0x06, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x12, 0x46, 0x0a, 0x09, 0x41,
	0x74, 0x6f, 0x6d, 0x69, 0x63, 0x41, 0x64, 0x64, 0x12, 0x1b, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e,
	0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c,
	0x79, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x4c, 0x6f, 0x61,
	0x64, 0x12, 0x1c, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x41, 0x74,
	0x6f, 0x6d, 0x69, 0x63, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x41, 0x74, 0x6f, 0x6d,
	0x69, 0x63, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c,
	0x0a, 0x0b, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x1d, 0x2e,
	0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x78,
	0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a,
	0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x53, 0x77, 0x61, 0x70, 0x12, 0x1c, 0x2e, 0x78, 0x69, 0x61,
	0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x53, 0x77, 0x61,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e,
	0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x53, 0x77, 0x61, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x14, 0x41, 0x74, 0x6f, 0x6d, 0x69,
	0x63, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x77, 0x61, 0x70, 0x12,
	0x26, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x41, 0x74, 0x6f, 0x6d,
	0x69, 0x63, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x77, 0x61, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61,
	0x6c, 0x6c, 0x79, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x65, 0x41, 0x6e, 0x64, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_atomic_ally_xiao_proto_rawDescOnce sync.Once
	file_atomic_ally_xiao_proto_rawDescData = file_atomic_ally_xiao_proto_rawDesc
)

func file_atomic_ally_xiao_proto_rawDescGZIP() []byte {
	file_atomic_ally_xiao_proto_rawDescOnce.Do(func() {
		file_atomic_ally_xiao_proto_rawDescData = protoimpl.X.CompressGZIP(file_atomic_ally_xiao_proto_rawDescData)
	})
	return file_atomic_ally_xiao_proto_rawDescData
}

var file_atomic_ally_xiao_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_atomic_ally_xiao_proto_goTypes = []any{
	(*AtomicAddRequest)(nil),             // 0: xiao.ally.AtomicAddRequest
	(*AtomicAddResponse)(nil),            // 1: xiao.ally.AtomicAddResponse
	(*AtomicCompareAndSwapRequest)(nil),  // 2: xiao.ally.AtomicCompareAndSwapRequest
	(*AtomicCompareAndSwapResponse)(nil), // 3: xiao.ally.AtomicCompareAndSwapResponse
	(*AtomicLoadRequest)(nil),            // 4: xiao.ally.AtomicLoadRequest
	(*AtomicLoadResponse)(nil),           // 5: xiao.ally.AtomicLoadResponse
	(*AtomicStoreRequest)(nil),           // 6: xiao.ally.AtomicStoreRequest
	(*AtomicStoreResponse)(nil),          // 7: xiao.ally.AtomicStoreResponse
	(*AtomicSwapRequest)(nil),            // 8: xiao.ally.AtomicSwapRequest
	(*AtomicSwapResponse)(nil),           // 9: xiao.ally.AtomicSwapResponse
}
var file_atomic_ally_xiao_proto_depIdxs = []int32{
	0, // 0: xiao.ally.Atomic.AtomicAdd:input_type -> xiao.ally.AtomicAddRequest
	4, // 1: xiao.ally.Atomic.AtomicLoad:input_type -> xiao.ally.AtomicLoadRequest
	6, // 2: xiao.ally.Atomic.AtomicStore:input_type -> xiao.ally.AtomicStoreRequest
	8, // 3: xiao.ally.Atomic.AtomicSwap:input_type -> xiao.ally.AtomicSwapRequest
	2, // 4: xiao.ally.Atomic.AtomicCompareAndSwap:input_type -> xiao.ally.AtomicCompareAndSwapRequest
	1, // 5: xiao.ally.Atomic.AtomicAdd:output_type -> xiao.ally.AtomicAddResponse
	5, // 6: xiao.ally.Atomic.AtomicLoad:output_type -> xiao.ally.AtomicLoadResponse
	7, // 7: xiao.ally.Atomic.AtomicStore:output_type -> xiao.ally.AtomicStoreResponse
	9, // 8: xiao.ally.Atomic.AtomicSwap:output_type -> xiao.ally.AtomicSwapResponse
	3, // 9: xiao.ally.Atomic.AtomicCompareAndSwap:output_type -> xiao.ally.AtomicCompareAndSwapResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_atomic_ally_xiao_proto_init() }
func file_atomic_ally_xiao_proto_init() {
	if File_atomic_ally_xiao_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_atomic_ally_xiao_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AtomicAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_ally_xiao_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AtomicAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_ally_xiao_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AtomicCompareAndSwapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_ally_xiao_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AtomicCompareAndSwapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_ally_xiao_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AtomicLoadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_ally_xiao_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AtomicLoadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_ally_xiao_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*AtomicStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_ally_xiao_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*AtomicStoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_ally_xiao_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*AtomicSwapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_ally_xiao_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*AtomicSwapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_atomic_ally_xiao_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atomic_ally_xiao_proto_goTypes,
		DependencyIndexes: file_atomic_ally_xiao_proto_depIdxs,
		MessageInfos:      file_atomic_ally_xiao_proto_msgTypes,
	}.Build()
	File_atomic_ally_xiao_proto = out.File
	file_atomic_ally_xiao_proto_rawDesc = nil
	file_atomic_ally_xiao_proto_goTypes = nil
	file_atomic_ally_xiao_proto_depIdxs = nil
}
