// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: cache.ally.xiao.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ns  string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Ttl uint64 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"` // ms
	Val []byte `protobuf:"bytes,4,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *CacheSetRequest) Reset() {
	*x = CacheSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetRequest) ProtoMessage() {}

func (x *CacheSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetRequest.ProtoReflect.Descriptor instead.
func (*CacheSetRequest) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{0}
}

func (x *CacheSetRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *CacheSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CacheSetRequest) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *CacheSetRequest) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

type CacheSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheSetResponse) Reset() {
	*x = CacheSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetResponse) ProtoMessage() {}

func (x *CacheSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetResponse.ProtoReflect.Descriptor instead.
func (*CacheSetResponse) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{1}
}

type CacheGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ns  string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CacheGetRequest) Reset() {
	*x = CacheGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetRequest) ProtoMessage() {}

func (x *CacheGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetRequest.ProtoReflect.Descriptor instead.
func (*CacheGetRequest) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{2}
}

func (x *CacheGetRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *CacheGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CacheGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Val   []byte `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *CacheGetResponse) Reset() {
	*x = CacheGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetResponse) ProtoMessage() {}

func (x *CacheGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetResponse.ProtoReflect.Descriptor instead.
func (*CacheGetResponse) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{3}
}

func (x *CacheGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CacheGetResponse) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

type CacheDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ns  string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CacheDelRequest) Reset() {
	*x = CacheDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheDelRequest) ProtoMessage() {}

func (x *CacheDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheDelRequest.ProtoReflect.Descriptor instead.
func (*CacheDelRequest) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{4}
}

func (x *CacheDelRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *CacheDelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CacheDelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheDelResponse) Reset() {
	*x = CacheDelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheDelResponse) ProtoMessage() {}

func (x *CacheDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheDelResponse.ProtoReflect.Descriptor instead.
func (*CacheDelResponse) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{5}
}

type CacheKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ns string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
}

func (x *CacheKeysRequest) Reset() {
	*x = CacheKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheKeysRequest) ProtoMessage() {}

func (x *CacheKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheKeysRequest.ProtoReflect.Descriptor instead.
func (*CacheKeysRequest) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{6}
}

func (x *CacheKeysRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

type CacheKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *CacheKeysResponse) Reset() {
	*x = CacheKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheKeysResponse) ProtoMessage() {}

func (x *CacheKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheKeysResponse.ProtoReflect.Descriptor instead.
func (*CacheKeysResponse) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{7}
}

func (x *CacheKeysResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type CacheCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ns string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
}

func (x *CacheCountRequest) Reset() {
	*x = CacheCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheCountRequest) ProtoMessage() {}

func (x *CacheCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheCountRequest.ProtoReflect.Descriptor instead.
func (*CacheCountRequest) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{8}
}

func (x *CacheCountRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

type CacheCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CacheCountResponse) Reset() {
	*x = CacheCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheCountResponse) ProtoMessage() {}

func (x *CacheCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheCountResponse.ProtoReflect.Descriptor instead.
func (*CacheCountResponse) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{9}
}

func (x *CacheCountResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CacheItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ns string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
}

func (x *CacheItemsRequest) Reset() {
	*x = CacheItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheItemsRequest) ProtoMessage() {}

func (x *CacheItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheItemsRequest.ProtoReflect.Descriptor instead.
func (*CacheItemsRequest) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{10}
}

func (x *CacheItemsRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

type CacheItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items map[string][]byte `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CacheItemsResponse) Reset() {
	*x = CacheItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheItemsResponse) ProtoMessage() {}

func (x *CacheItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheItemsResponse.ProtoReflect.Descriptor instead.
func (*CacheItemsResponse) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{11}
}

func (x *CacheItemsResponse) GetItems() map[string][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

type CacheFlushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ns string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
}

func (x *CacheFlushRequest) Reset() {
	*x = CacheFlushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheFlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheFlushRequest) ProtoMessage() {}

func (x *CacheFlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheFlushRequest.ProtoReflect.Descriptor instead.
func (*CacheFlushRequest) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{12}
}

func (x *CacheFlushRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

type CacheFlushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheFlushResponse) Reset() {
	*x = CacheFlushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheFlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheFlushResponse) ProtoMessage() {}

func (x *CacheFlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheFlushResponse.ProtoReflect.Descriptor instead.
func (*CacheFlushResponse) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{13}
}

type CacheExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ns  string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CacheExistsRequest) Reset() {
	*x = CacheExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheExistsRequest) ProtoMessage() {}

func (x *CacheExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheExistsRequest.ProtoReflect.Descriptor instead.
func (*CacheExistsRequest) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{14}
}

func (x *CacheExistsRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *CacheExistsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CacheExistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *CacheExistsResponse) Reset() {
	*x = CacheExistsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_ally_xiao_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheExistsResponse) ProtoMessage() {}

func (x *CacheExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_ally_xiao_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheExistsResponse.ProtoReflect.Descriptor instead.
func (*CacheExistsResponse) Descriptor() ([]byte, []int) {
	return file_cache_ally_xiao_proto_rawDescGZIP(), []int{15}
}

func (x *CacheExistsResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_cache_ally_xiao_proto protoreflect.FileDescriptor

var file_cache_ally_xiao_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x78, 0x69, 0x61,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c,
	0x6c, 0x79, 0x22, 0x57, 0x0a, 0x0f, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x12, 0x0a, 0x10, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x33, 0x0a, 0x0f, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x3a, 0x0a, 0x10, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x76, 0x61, 0x6c,
	0x22, 0x33, 0x0a, 0x0f, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x22, 0x27, 0x0a,
	0x11, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x43, 0x61, 0x63, 0x68, 0x65, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x22, 0x2a, 0x0a, 0x12, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x23, 0x0a, 0x11, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x22, 0x8e, 0x01, 0x0a,
	0x12, 0x43, 0x61, 0x63, 0x68, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x23, 0x0a,
	0x11, 0x43, 0x61, 0x63, 0x68, 0x65, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6e, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x61, 0x63, 0x68, 0x65, 0x46, 0x6c, 0x75, 0x73, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x36, 0x0a, 0x12, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x2b, 0x0a, 0x13, 0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0xcd, 0x04,
	0x0a, 0x05, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x53, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e,
	0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79,
	0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x43, 0x0a, 0x08, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x65, 0x6c, 0x12, 0x1a, 0x2e,
	0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x78, 0x69, 0x61, 0x6f,
	0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4b,
	0x65, 0x79, 0x73, 0x12, 0x1b, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49,
	0x0a, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x78,
	0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x78, 0x69, 0x61,
	0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1c, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61,
	0x6c, 0x6c, 0x79, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c,
	0x79, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x46, 0x6c, 0x75,
	0x73, 0x68, 0x12, 0x1c, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4c, 0x0a, 0x0b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x1d,
	0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cache_ally_xiao_proto_rawDescOnce sync.Once
	file_cache_ally_xiao_proto_rawDescData = file_cache_ally_xiao_proto_rawDesc
)

func file_cache_ally_xiao_proto_rawDescGZIP() []byte {
	file_cache_ally_xiao_proto_rawDescOnce.Do(func() {
		file_cache_ally_xiao_proto_rawDescData = protoimpl.X.CompressGZIP(file_cache_ally_xiao_proto_rawDescData)
	})
	return file_cache_ally_xiao_proto_rawDescData
}

var file_cache_ally_xiao_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_cache_ally_xiao_proto_goTypes = []any{
	(*CacheSetRequest)(nil),     // 0: xiao.ally.CacheSetRequest
	(*CacheSetResponse)(nil),    // 1: xiao.ally.CacheSetResponse
	(*CacheGetRequest)(nil),     // 2: xiao.ally.CacheGetRequest
	(*CacheGetResponse)(nil),    // 3: xiao.ally.CacheGetResponse
	(*CacheDelRequest)(nil),     // 4: xiao.ally.CacheDelRequest
	(*CacheDelResponse)(nil),    // 5: xiao.ally.CacheDelResponse
	(*CacheKeysRequest)(nil),    // 6: xiao.ally.CacheKeysRequest
	(*CacheKeysResponse)(nil),   // 7: xiao.ally.CacheKeysResponse
	(*CacheCountRequest)(nil),   // 8: xiao.ally.CacheCountRequest
	(*CacheCountResponse)(nil),  // 9: xiao.ally.CacheCountResponse
	(*CacheItemsRequest)(nil),   // 10: xiao.ally.CacheItemsRequest
	(*CacheItemsResponse)(nil),  // 11: xiao.ally.CacheItemsResponse
	(*CacheFlushRequest)(nil),   // 12: xiao.ally.CacheFlushRequest
	(*CacheFlushResponse)(nil),  // 13: xiao.ally.CacheFlushResponse
	(*CacheExistsRequest)(nil),  // 14: xiao.ally.CacheExistsRequest
	(*CacheExistsResponse)(nil), // 15: xiao.ally.CacheExistsResponse
	nil,                         // 16: xiao.ally.CacheItemsResponse.ItemsEntry
}
var file_cache_ally_xiao_proto_depIdxs = []int32{
	16, // 0: xiao.ally.CacheItemsResponse.items:type_name -> xiao.ally.CacheItemsResponse.ItemsEntry
	0,  // 1: xiao.ally.Cache.CacheSet:input_type -> xiao.ally.CacheSetRequest
	2,  // 2: xiao.ally.Cache.CacheGet:input_type -> xiao.ally.CacheGetRequest
	4,  // 3: xiao.ally.Cache.CacheDel:input_type -> xiao.ally.CacheDelRequest
	6,  // 4: xiao.ally.Cache.CacheKeys:input_type -> xiao.ally.CacheKeysRequest
	8,  // 5: xiao.ally.Cache.CacheCount:input_type -> xiao.ally.CacheCountRequest
	10, // 6: xiao.ally.Cache.CacheItems:input_type -> xiao.ally.CacheItemsRequest
	12, // 7: xiao.ally.Cache.CacheFlush:input_type -> xiao.ally.CacheFlushRequest
	14, // 8: xiao.ally.Cache.CacheExists:input_type -> xiao.ally.CacheExistsRequest
	1,  // 9: xiao.ally.Cache.CacheSet:output_type -> xiao.ally.CacheSetResponse
	3,  // 10: xiao.ally.Cache.CacheGet:output_type -> xiao.ally.CacheGetResponse
	5,  // 11: xiao.ally.Cache.CacheDel:output_type -> xiao.ally.CacheDelResponse
	7,  // 12: xiao.ally.Cache.CacheKeys:output_type -> xiao.ally.CacheKeysResponse
	9,  // 13: xiao.ally.Cache.CacheCount:output_type -> xiao.ally.CacheCountResponse
	11, // 14: xiao.ally.Cache.CacheItems:output_type -> xiao.ally.CacheItemsResponse
	13, // 15: xiao.ally.Cache.CacheFlush:output_type -> xiao.ally.CacheFlushResponse
	15, // 16: xiao.ally.Cache.CacheExists:output_type -> xiao.ally.CacheExistsResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_cache_ally_xiao_proto_init() }
func file_cache_ally_xiao_proto_init() {
	if File_cache_ally_xiao_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cache_ally_xiao_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CacheDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CacheDelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CacheKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CacheKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CacheCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CacheCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CacheItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*CacheItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*CacheFlushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CacheFlushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*CacheExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_ally_xiao_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*CacheExistsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cache_ally_xiao_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_ally_xiao_proto_goTypes,
		DependencyIndexes: file_cache_ally_xiao_proto_depIdxs,
		MessageInfos:      file_cache_ally_xiao_proto_msgTypes,
	}.Build()
	File_cache_ally_xiao_proto = out.File
	file_cache_ally_xiao_proto_rawDesc = nil
	file_cache_ally_xiao_proto_goTypes = nil
	file_cache_ally_xiao_proto_depIdxs = nil
}
