// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: locker.ally.xiao.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockerLockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LockerLockRequest) Reset() {
	*x = LockerLockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerLockRequest) ProtoMessage() {}

func (x *LockerLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerLockRequest.ProtoReflect.Descriptor instead.
func (*LockerLockRequest) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{0}
}

func (x *LockerLockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LockerLockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LockerLockResponse) Reset() {
	*x = LockerLockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerLockResponse) ProtoMessage() {}

func (x *LockerLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerLockResponse.ProtoReflect.Descriptor instead.
func (*LockerLockResponse) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{1}
}

type LockerRLockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LockerRLockRequest) Reset() {
	*x = LockerRLockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerRLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerRLockRequest) ProtoMessage() {}

func (x *LockerRLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerRLockRequest.ProtoReflect.Descriptor instead.
func (*LockerRLockRequest) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{2}
}

func (x *LockerRLockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LockerRLockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LockerRLockResponse) Reset() {
	*x = LockerRLockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerRLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerRLockResponse) ProtoMessage() {}

func (x *LockerRLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerRLockResponse.ProtoReflect.Descriptor instead.
func (*LockerRLockResponse) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{3}
}

type LockerTryLockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Timeout uint64 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"` // ms
}

func (x *LockerTryLockRequest) Reset() {
	*x = LockerTryLockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerTryLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerTryLockRequest) ProtoMessage() {}

func (x *LockerTryLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerTryLockRequest.ProtoReflect.Descriptor instead.
func (*LockerTryLockRequest) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{4}
}

func (x *LockerTryLockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LockerTryLockRequest) GetTimeout() uint64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type LockerTryLockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acquired bool `protobuf:"varint,1,opt,name=acquired,proto3" json:"acquired,omitempty"`
}

func (x *LockerTryLockResponse) Reset() {
	*x = LockerTryLockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerTryLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerTryLockResponse) ProtoMessage() {}

func (x *LockerTryLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerTryLockResponse.ProtoReflect.Descriptor instead.
func (*LockerTryLockResponse) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{5}
}

func (x *LockerTryLockResponse) GetAcquired() bool {
	if x != nil {
		return x.Acquired
	}
	return false
}

type LockerTryRLockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Timeout uint64 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"` // ms
}

func (x *LockerTryRLockRequest) Reset() {
	*x = LockerTryRLockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerTryRLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerTryRLockRequest) ProtoMessage() {}

func (x *LockerTryRLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerTryRLockRequest.ProtoReflect.Descriptor instead.
func (*LockerTryRLockRequest) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{6}
}

func (x *LockerTryRLockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LockerTryRLockRequest) GetTimeout() uint64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type LockerTryRLockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acquired bool `protobuf:"varint,1,opt,name=acquired,proto3" json:"acquired,omitempty"`
}

func (x *LockerTryRLockResponse) Reset() {
	*x = LockerTryRLockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerTryRLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerTryRLockResponse) ProtoMessage() {}

func (x *LockerTryRLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerTryRLockResponse.ProtoReflect.Descriptor instead.
func (*LockerTryRLockResponse) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{7}
}

func (x *LockerTryRLockResponse) GetAcquired() bool {
	if x != nil {
		return x.Acquired
	}
	return false
}

type LockerUnlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LockerUnlockRequest) Reset() {
	*x = LockerUnlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerUnlockRequest) ProtoMessage() {}

func (x *LockerUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerUnlockRequest.ProtoReflect.Descriptor instead.
func (*LockerUnlockRequest) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{8}
}

func (x *LockerUnlockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LockerUnlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LockerUnlockResponse) Reset() {
	*x = LockerUnlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerUnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerUnlockResponse) ProtoMessage() {}

func (x *LockerUnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerUnlockResponse.ProtoReflect.Descriptor instead.
func (*LockerUnlockResponse) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{9}
}

type LockerRUnlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LockerRUnlockRequest) Reset() {
	*x = LockerRUnlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerRUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerRUnlockRequest) ProtoMessage() {}

func (x *LockerRUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerRUnlockRequest.ProtoReflect.Descriptor instead.
func (*LockerRUnlockRequest) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{10}
}

func (x *LockerRUnlockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LockerRUnlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LockerRUnlockResponse) Reset() {
	*x = LockerRUnlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerRUnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerRUnlockResponse) ProtoMessage() {}

func (x *LockerRUnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerRUnlockResponse.ProtoReflect.Descriptor instead.
func (*LockerRUnlockResponse) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{11}
}

type LockerQueuesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LockerQueuesRequest) Reset() {
	*x = LockerQueuesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerQueuesRequest) ProtoMessage() {}

func (x *LockerQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerQueuesRequest.ProtoReflect.Descriptor instead.
func (*LockerQueuesRequest) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{12}
}

func (x *LockerQueuesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LockerQueuesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R int64 `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	W int64 `protobuf:"varint,2,opt,name=w,proto3" json:"w,omitempty"`
}

func (x *LockerQueuesResponse) Reset() {
	*x = LockerQueuesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_locker_ally_xiao_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerQueuesResponse) ProtoMessage() {}

func (x *LockerQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locker_ally_xiao_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerQueuesResponse.ProtoReflect.Descriptor instead.
func (*LockerQueuesResponse) Descriptor() ([]byte, []int) {
	return file_locker_ally_xiao_proto_rawDescGZIP(), []int{13}
}

func (x *LockerQueuesResponse) GetR() int64 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *LockerQueuesResponse) GetW() int64 {
	if x != nil {
		return x.W
	}
	return 0
}

var File_locker_ally_xiao_proto protoreflect.FileDescriptor

var file_locker_ally_xiao_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x78, 0x69,
	0x61, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61,
	0x6c, 0x6c, 0x79, 0x22, 0x27, 0x0a, 0x11, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x14, 0x0a, 0x12,
	0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x4c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x15, 0x0a, 0x13,
	0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x44, 0x0a, 0x14, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x54, 0x72, 0x79,
	0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x33, 0x0a, 0x15, 0x4c, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x54, 0x72, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x45,
	0x0a, 0x15, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x54, 0x72, 0x79, 0x52, 0x4c, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x34, 0x0a, 0x16, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x54,
	0x72, 0x79, 0x52, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x29, 0x0a, 0x13, 0x4c,
	0x6f, 0x63, 0x6b, 0x65, 0x72, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72,
	0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a,
	0x0a, 0x14, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x52, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x32,
	0x0a, 0x14, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x01, 0x77, 0x32, 0xc2, 0x04, 0x0a, 0x06, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x49, 0x0a,
	0x0a, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x1c, 0x2e, 0x78, 0x69,
	0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x4c, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x78, 0x69, 0x61, 0x6f,
	0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x4c, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x52, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x1d, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61,
	0x6c, 0x6c, 0x79, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x4c, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c,
	0x6c, 0x79, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72,
	0x54, 0x72, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x1f, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61,
	0x6c, 0x6c, 0x79, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x54, 0x72, 0x79, 0x4c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e,
	0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x54, 0x72, 0x79, 0x4c, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x4c, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x54, 0x72, 0x79, 0x52, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x20, 0x2e, 0x78,
	0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x54,
	0x72, 0x79, 0x52, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x54, 0x72, 0x79, 0x52, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x55, 0x6e, 0x6c, 0x6f, 0x63,
	0x6b, 0x12, 0x1e, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x4c, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e, 0x4c, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x55, 0x6e, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x1f, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79, 0x2e,
	0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c, 0x6c, 0x79,
	0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c,
	0x6c, 0x79, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x2e, 0x61, 0x6c,
	0x6c, 0x79, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_locker_ally_xiao_proto_rawDescOnce sync.Once
	file_locker_ally_xiao_proto_rawDescData = file_locker_ally_xiao_proto_rawDesc
)

func file_locker_ally_xiao_proto_rawDescGZIP() []byte {
	file_locker_ally_xiao_proto_rawDescOnce.Do(func() {
		file_locker_ally_xiao_proto_rawDescData = protoimpl.X.CompressGZIP(file_locker_ally_xiao_proto_rawDescData)
	})
	return file_locker_ally_xiao_proto_rawDescData
}

var file_locker_ally_xiao_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_locker_ally_xiao_proto_goTypes = []any{
	(*LockerLockRequest)(nil),      // 0: xiao.ally.LockerLockRequest
	(*LockerLockResponse)(nil),     // 1: xiao.ally.LockerLockResponse
	(*LockerRLockRequest)(nil),     // 2: xiao.ally.LockerRLockRequest
	(*LockerRLockResponse)(nil),    // 3: xiao.ally.LockerRLockResponse
	(*LockerTryLockRequest)(nil),   // 4: xiao.ally.LockerTryLockRequest
	(*LockerTryLockResponse)(nil),  // 5: xiao.ally.LockerTryLockResponse
	(*LockerTryRLockRequest)(nil),  // 6: xiao.ally.LockerTryRLockRequest
	(*LockerTryRLockResponse)(nil), // 7: xiao.ally.LockerTryRLockResponse
	(*LockerUnlockRequest)(nil),    // 8: xiao.ally.LockerUnlockRequest
	(*LockerUnlockResponse)(nil),   // 9: xiao.ally.LockerUnlockResponse
	(*LockerRUnlockRequest)(nil),   // 10: xiao.ally.LockerRUnlockRequest
	(*LockerRUnlockResponse)(nil),  // 11: xiao.ally.LockerRUnlockResponse
	(*LockerQueuesRequest)(nil),    // 12: xiao.ally.LockerQueuesRequest
	(*LockerQueuesResponse)(nil),   // 13: xiao.ally.LockerQueuesResponse
}
var file_locker_ally_xiao_proto_depIdxs = []int32{
	0,  // 0: xiao.ally.Locker.LockerLock:input_type -> xiao.ally.LockerLockRequest
	2,  // 1: xiao.ally.Locker.LockerRLock:input_type -> xiao.ally.LockerRLockRequest
	4,  // 2: xiao.ally.Locker.LockerTryLock:input_type -> xiao.ally.LockerTryLockRequest
	6,  // 3: xiao.ally.Locker.LockerTryRLock:input_type -> xiao.ally.LockerTryRLockRequest
	8,  // 4: xiao.ally.Locker.LockerUnlock:input_type -> xiao.ally.LockerUnlockRequest
	10, // 5: xiao.ally.Locker.LockerRUnlock:input_type -> xiao.ally.LockerRUnlockRequest
	12, // 6: xiao.ally.Locker.LockerQueues:input_type -> xiao.ally.LockerQueuesRequest
	1,  // 7: xiao.ally.Locker.LockerLock:output_type -> xiao.ally.LockerLockResponse
	3,  // 8: xiao.ally.Locker.LockerRLock:output_type -> xiao.ally.LockerRLockResponse
	5,  // 9: xiao.ally.Locker.LockerTryLock:output_type -> xiao.ally.LockerTryLockResponse
	7,  // 10: xiao.ally.Locker.LockerTryRLock:output_type -> xiao.ally.LockerTryRLockResponse
	9,  // 11: xiao.ally.Locker.LockerUnlock:output_type -> xiao.ally.LockerUnlockResponse
	11, // 12: xiao.ally.Locker.LockerRUnlock:output_type -> xiao.ally.LockerRUnlockResponse
	13, // 13: xiao.ally.Locker.LockerQueues:output_type -> xiao.ally.LockerQueuesResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_locker_ally_xiao_proto_init() }
func file_locker_ally_xiao_proto_init() {
	if File_locker_ally_xiao_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_locker_ally_xiao_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LockerLockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LockerLockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LockerRLockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LockerRLockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LockerTryLockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LockerTryLockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*LockerTryRLockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*LockerTryRLockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*LockerUnlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*LockerUnlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*LockerRUnlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*LockerRUnlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*LockerQueuesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_locker_ally_xiao_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*LockerQueuesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_locker_ally_xiao_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_locker_ally_xiao_proto_goTypes,
		DependencyIndexes: file_locker_ally_xiao_proto_depIdxs,
		MessageInfos:      file_locker_ally_xiao_proto_msgTypes,
	}.Build()
	File_locker_ally_xiao_proto = out.File
	file_locker_ally_xiao_proto_rawDesc = nil
	file_locker_ally_xiao_proto_goTypes = nil
	file_locker_ally_xiao_proto_depIdxs = nil
}
