#!/bin/sh

_ROOT="$(pwd)" && cd "$(dirname "$0")" && ROOT="$(pwd)"
PJROOT="$ROOT"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:$HOME/go/bin:$PATH"

tlog() {
    echo "$(date '+%Y-%m-%d %H:%M:%S %Z') > $*"
}

# env check
if ! which protoc >/dev/null 2>&1; then
    tlog "Command [protoc] not found"
    exit 1
fi
if ! which protoc-gen-go >/dev/null 2>&1; then
    tlog "Command [protoc-gen-go] not found"
    tlog "Try: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest"
    exit 1
fi
if ! which protoc-gen-go-grpc >/dev/null 2>&1; then
    tlog "Command [protoc-gen-go-grpc] not found"
    tlog "Try: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest"
    exit 1
fi
VER="$(protoc --version | awk '{print $2}' | cut -d. -f1)"
if [ "$VER" -le 2 ]; then
	tlog "Fatal: Only support protoc >= 3"
	exit 1
else
	VER="$(echo | protoc-gen-go --version 2>/dev/null | sed -n -E 's/.*[[:space:]]+v([0-9]+(\.[0-9]+)?).*/\1/p')"
    if [ -z "$VER" -o "$(echo "$VER<1.27" | bc)" -eq 1 ]; then
        tlog "Fatal: protoc-gen-go version must >= v1.27"
        tlog "Try:   go install google.golang.org/protobuf/cmd/protoc-gen-go@latest"
        exit 1
    fi
	VER="$(echo | protoc-gen-go-grpc --version 2>/dev/null | sed -n -E 's/.*[[:space:]]+([0-9]+(\.[0-9]+)?).*/\1/p')"
    if [ -z "$VER" -o "$(echo "$VER<1.1" | bc)" -eq 1 ]; then
        tlog "Fatal: protoc-gen-go-grpc version must >= v1.1"
        tlog "Try:   go install google.golang.org/protobuf/cmd/protoc-gen-go@latest"
        exit 1
    fi
fi

if [ "$1" = "clean" ]; then
    rm -f *.pb.go
    tlog "Done."
    exit 0
fi

tlog "Compiling to go code..."
protoc --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:. *.proto

tlog "Done."
